#+LaTeX_CLASS: UoM-draft-org-article
#+LaTeX_CLASS_OPTIONS: [a4paper,11pt,twopage]
#+OPTIONS: toc:nil H:5 author:nil
#+TITLE: Synaptic Organisation in the Cochlear Nucleus
#+DATE:
#+AUTHOR: Michael A Eager
#+LATEX_HEADER:\usepackage[sort,round,numbers]{natbib}
#  #+LATEX_HEADER:\usepackage{wasysym,latexsym,amssymb,amsmath}
#+LATEX_HEADER:\usepackage[colorlinks,linkcolor=black,citecolor=black,urlcolor=black]{hyperref}
#+BIBLIOGRAPHY: MyBib unsrtnat
#+TEXT:        \setcounter{chapter}{1}
#+TEXT:        \chapter{Synaptic Organisation in the Cochlear Nucleus}

* Prelude 							   :noexport:

#+begin_elisp:
(setq org-latex-to-pdf-process '("lapdf SynapticOrganisation"))
(UoM-org-options)
#+end_elisp


* Introduction
#Synaptic organisation modulating T stellate cells

Advances in histological and pharmacological labelling techniques have produced
a flood of information about the anatomy, physiology, immunohistochemistry,
pharmacology and intrinsic membrane properties of the different cell types in
the CN. The synaptic organisation of cells in the cochlear nucleus of has been
examined in detail in various species (cat:
\citep*{Cant:1981,TolbertMorest:1982,SaintMorestEtAl:1989}, mice:
\citep*{WickesbergOertel:1988,WickesbergOertel:1990,WickesbergWhitlonEtAl:1991},
Guinea pig: \citep*{JuizHelfertEtAl:1996,OstapoffBensonEtAl:1997}, Rat:
\citep*{FriedlandPongstapornEtAl:2003,RubioJuiz:2004}.  Physiological studies
combined with labelling have given greater certainty to correlations between
physiological response types and morphological cell types
\citep[e.g. ][]{SmithRhode:1989,OstapoffFengEtAl:1994,PalmerWallaceEtAl:2003,ArnottWallaceEtAl:2004}.
Intracellular recordings have ascertained the electrical properties and the
different synaptic inputs of TS, DS and TV cells
\citep{FerragamoGoldingEtAl:1998a,ZhangOertel:1993}.  Descriptions of current
dynamics for synaptic receptors \citep{GardnerTrussellEtAl:1999,HartyManis:1998}
and membrane channels
\citep{RothmanManis:2003,RothmanManis:2003a,RothmanManis:2003b} specific to the
VCN enable accurate mathematical models at the cell and synaptic level.  With
this information a realistic biological model of the stellate network is
attainable and can provide further insights into processing of acoustic
information.


* Receptors and Neurotransmitters
** Glutamatergic AMPA synapses

Type I auditory nerve fibre synapses form glutamatergic AMPA receptors

\citep{FexWenthold:1976,
AdamsMugnaini:1987,GrandesStreit:1989,SchweitzerJensenEtAl:1991,HunterPetraliaEtAl:1993,
WrightBlackstoneEtAl:1996,PetraliaWangEtAl:1996,
NekiOhishiEtAl:1996,HackneyOsenEtAl:1996,RubioWenthold:1997,PetraliaWangEtAl:1997,LevinKubkeEtAl:1997,
WangWentholdEtAl:1998,OhishiNekiEtAl:1998,BilakMorest:1998,
PetraliaRubioEtAl:2000,KoradaSchwartz:2000,
KemmerVater:2001,SrinivasanFriaufEtAl:2004,RubioJuiz:2004,Rubio:2005,Rubio:2006,
ItoBishopEtAl:2011}


 \citep{FerragamoGoldingEtAl:1998a,WentholdHunterEtAl:1993}.  Histological measures
 of labelled T stellate cells show the presence of glutamate and glutamine antibodies
 \citep{HackneyOsenEtAl:1990,WentholdHunterEtAl:1993}.  More advanced measures using
 electron microscopy reveal AMPA subunits, unique to the cochlear nucleus, apposing
 TS cells \citep{WangWentholdEtAl:1998}.  
Pharmacologic experiments have also
 confirmed monosynaptic EPSPs from AN shocks are be blocked by the AMPA antagonist
 DNQX \citep{FerragamoGoldingEtAl:1998a}. Glutamatergic NMDA receptors may also be present at ANF synapses
 \citep[mice][]{FerragamoGoldingEtAl:1998a} and can be activated to produce large
 synaptic currents \citep{CaoOertel:2010}.  

Whole cell patch recordings show NMDA
 dominance over AMPA at birth reverses during development, leaving little to no
 observable NMDA EPSCs at the soma in mature rats \citep{BellinghamLimEtAl:1998}.
# %\citep{Oertel:1983}
 Five percent of ANFs are unmyelinated type II fibres (cat: \citep{KiangRhoEtAl:1982},mice: \citep{Ehret:1979}). 
 possibly mediated by NMDA receptors or mossy fiber-like endings with reduced glutamate re-uptake JosephsonMorest:2003
 the lack of
 \citep{BensonBrown:2004,Ryugo:2008,RyugoHaenggeliEtAl:2003,RyugoParks:2003}.
 (cats: Kiang et al. 1982; mice: Ehret 1979)


** Glycinergic synapses

Evidence of glycine in the cochlear nucleus, through staining or
 immunohostochemistry, has been studied in many species including guinea pigs
 \citep{JuizHelfertEtAl:1996a,HelfertBonneauEtAl:1989,Wenthold:1987,WentholdHuieEtAl:1987,AltschulerBetzEtAl:1986,SaintBensonEtAl:1991,KolstonOsenEtAl:1992,PeyretCampistronEtAl:1987,Alibardi:2003a,MahendrasingamWallamEtAl:2004,MahendrasingamWallamEtAl:2000,BabalianJacommeEtAl:2002},
 rats
 \citep{OsenLopezEtAl:1991,Mugnaini:1985,AokiSembaEtAl:1988,GatesWeedmanEtAl:1996,Alibardi:2003,LimOleskevichEtAl:2003,SrinivasanFriaufEtAl:2004,DoucetRossEtAl:1999},
 mice \citep{WickesbergWhitlonEtAl:1991,LimOleskevichEtAl:2003,YangDoievEtAl:2002},
 cats \citep{OsenOttersenEtAl:1990,SmithRhode:1989}, baboons
 \citep{MooreOsenEtAl:1996}, gerbils \citep{GleichVater:1998}, and bats
 \citep{KemmerVater:2001a}.

Glycine GlyR receptors (mouse [\citep{FerragamoGoldingEtAl:1998a}]).
Flat vesicles (Glycine) apposed to TS units (cat [\citep{SmithRhode:1989}])
Could be mixed Gly/GABA [\citep{AltschulerJuizEtAl:1993}], most likely from periolivary terminals


The fast dynamics of the glycinergic synapse is essential for transmitting
temporal information to higher centres.  Early studies in VCN slice preparations in
the VCN estimated the decay time constant as fast as 1.6 ms
\citep[mouse][]{Oertel:1983}, but several studies found values toward 5.3 ms
(\citep*[mouse][]{OertelWickesberg:1993,WickesbergOertel:1993}, 
\citep*[guinea~pig][]{HartyManis:1998}) In more recent developments, spontaneous IPSCs in
MNTB neurons in rats (a close analogue of neurons in the VCN core) provide an
accurate measure or the dynamics of the receptor ($\tau$). The weighted decay
time constant of IPSCs in young rats ($3.9 \mathrm{ms} \pm 0.5$) is a
combination of ($\tau_{\textrm{fast}}$ and $\tau_{\textrm{slow}}$)
\citet{AwatramaniTurecekEtAl:2004} measured the miniature IPSCs in mature rats
and found the fast exponential dominated ($\tau_{\textrm{fast}}= 2.1 \pm 0.1$ msec).

Even after high frequency train stimuli, glycinergic IPSCs returned to a steady
decay of $2.8 \pm 0.4$ ms (MNTB neurons at 37°C in P20--P25 rats
\citep*{AwatramaniTurecekEtAl:2009}.


# Evoked IPSCs had an average $\tau_{\textrm{fast}}$ of 2.9 0.3 msec (96% of the fit) and a $\tau_{\textrm{slow}}$ of 12.3 16.4 msec.

# At physiological temperatures, glycinergic mIPSCs were fast as those measured at
# room temperature ($\tau_{\textrm{fast}}=0.8 \pm 0.2$ msec). The evoked IPSCs
# were also briefer at 37°C ($\tau_{\textrm{fast}}=1.0 \pm 0.2$ msec) (Fig. 2
# A).


The rise time (10\%-90\%) of IPSCs at room temp is faster in AVCN glycinergic
mIPSCs ($0.46 \pm 0.05$ ms) compared to MNTB ($0.60 \pm 0.03$ ms)
\citep{LimOleskevichEtAl:2003}, and the decay time constant equates to 2.5 ms at
body temperature.

Rise 0.4 ms, Decay 2.5 ms (spontaneous IPSCs in rat MNTB neurons,
\citep{AwatramaniTurecekEtAl:2005}) The rise time of glycinergic IPSCs was
consistent across rodents also measured $0.46 \pm 0.05$ ms spontaneous IPSCs In
AVCN bushy cells in mice \citep{LimOleskevichEtAl:2003}.


# Decay  5.47 $\pm$0.19 (very young MNTB rat [\citep{AwatramaniTurecekEtAl:2005}])
# Decay 6--13 ms (Slice prep 30 C degrees; VCN guinea pig [\citep{HartyManis:1998}]).
# Activation to 1mM Gly 2.0$\pm$1.2 ms (range 0.8 to 4.6 ms), deactivation to 1s Gly \tau_[[latex:textrm][fast]] 15.5 ms and \tau_[[latex:textrm][slow]]    73.4 ms (MNTB mouse [\citep{LeaoOleskevichEtAl:2004}]).

Decay 1.6 ms \citep[mouse VCN,]{Oertel:1983}
Decay 5.4 ms [\citep{OertelWickesberg:1993,WickesbergOertel:1993}]
Activation $2.0 \pm 1.2$ ms Decay 5.3 ms (Gly puffs at 22°C (Q_{10} 2.1) in  guinea pig VCN [\citep{HartyManis:1998}])

** GABAergic GABA_A synapses

# GABAergic GABA$_{\textrm{A}}$ receptor  (bicuculine-sensitive VCN T stellate cell, mouse slice preparation [\citenum{FerragamoGoldingEtAl:1998}], chinchilla [\citenum{JosephsonMorest:1998}])
# Ferragamo et al. 1998 found no GABAergic IPSPs but the cells were still sensitive to bicuculine

GABA staining in the VCN \citep{SaintMorestEtAl:1989}


Golgi cells are the only GABAergic neuron in the VCN and lie within the
 granule cell domains around the VCN and terminate near the fine distal
 dendrites of T and D stellate cells. Despite the lack of IPSPs or IPSCs, the
 presence of GABA_A receptors and their response changes to bicuculine in
 isolated VCN slices, the evidence for synatpic conncectivity between Golgi
 cells and the two VCN stellate cells is strong
 \citep{WuOertel:1986,OertelWickesberg:1993,FerragamoGoldingEtAl:1998a}.

# Surprisingly, in the adult MNTB, neurons express a “slow” GABAA
# receptor containing the \alpha{}3 subunit (Campos et al. 2001). Consis-
# tent with these findings, decay kinetics of GABAergic mIPSCs
# were relatively slow (\tau_d = 20 ms) compared with those synapses
# where the “fast” (\tau_d = 10 ms) \alpha{}1 subunits predominate (Bosman
# et al. 2002; Hollrigel and Soltesz 1997; Vicini et al. 2001). Hence,
# in the MNTB, glycine receptors are used in fast signaling path-
# ways, whereas GABAergic systems may mediate tonic inhibition
# through slower GABA_A receptors.





# Markers of GABAergic neurotransmission in the cochlear
# nucleus reveal the presence of both cell bodies and terminals
# that could be GABAergic. Antibodies to GABA conjugates
# and to glutamate decarboxylase (GAD) generally label neu-
# rons that are functionally GABAergic. Occasionally GAD
# and GABA are associated with neurons that are functionally
# glycinergic; cartwheel cells of the DCN, for example, are
# labeled for GABA and GAD yet seem to be glycinergic
# (Golding and Oertel 1997; Golding et al. 1996). Function-
# ally GABAergic neurons and their terminals are labeled con-
# sistently for GABA and GAD, however, indicating that the
# source of GABAergic input in T stellate cells would be
# expected to be labeled. GABAergic input could arise from
# neurons intrinsic to the cochlear nuclei or from sites external
# to the nucleus, such as the superior olivary nucleus (Saint
# Marie et al. 1989). Only GABAergic neurons in the cochlear
# nuclei can function in polysynaptic circuits in slices as was
# observed in the present study, however, isolated terminals
# of extrinsic sources cannot be activated synaptically.
# Labeling for GAD and GABA is associated strongly with
# regions that contain granule cells, the molecular and fusiform
# cell layers of the DCN and the superficial granule cell do-
# main of the VCN. In cats and guinea pigs, antibodies to
# GABA conjugates and to GAD, a biosynthetic enzyme, have
# been shown to label specific groups of cells and terminals
# (GABA: Kolston et al. 1992; Osen et al. 1990; Wenthold et
# al. 1986; GAD: Adams and Mugnaini 1987; Moore and
# Moore 1987; Mugnaini 1985; Saint Marie et al. 1989). In
# the DCN, the majority of cell bodies and puncta that were
# labeled with antibodies against GABA and GAD lie in the
# superficial and fusiform cell layers (Adams and Mugnaini
# 1987; Kolston et al. 1992; Moore and Moore 1987; Mugnaini
# 1985; Osen et al. 1990; Saint Marie et al. 1989; Wenthold
# et al. 1986). Labeled neurons are cartwheel, stellate, and
# Golgi cells. As none of these neurons make direct or indirect
# connections with the VCN, it is unlikely that cartwheel,
# superficial stellate or Golgi cells of the DCN contribute to
# GABAergic inhibition in T stellate cells of the VCN.
# GABAergic input to T stellate cells of the VCN could
# arise from Golgi cells in the superficial granule cell domain
# either mono- or disynaptically. Labeled cell bodies identified
# as Golgi cells were observed to be associated with the super-
# ficial granule cell layer (Mugnaini 1985). These neurons
# terminate locally in the superficial granule cell layer with
# very dense terminal arbors that abut the underlying large
# cell area (Ferragamo et al. 1997). The dendrites of D stellate
# cells lie just beneath the superficial granule cell domain,
# poised to be contacted by Golgi cells proximally and distally,
# indicating that D stellate cells could mediate GABAergic
# responses. Furthermore, some of the branches of the distal
# dendrites of T stellate cells approach the superficial granule
# cell domain. If Golgi cells contact T stellate cells directly,
# those contacts can only be on distal dendrites. In contrast
# with glycinergic IPSPs, GABAergic IPSPs were not promi-
# nent in T or D stellate cells; IPSPs that remained in the
# presence of strychnine were small and inconspicuous, if
# present. There are four possible reasons for this observation:
# the synaptic currents associated with GABAergic inputs
# were relatively slower and weaker, they were generated rela-
# tively far from the somatic recording site, they were medi-
# ated through an excitatory interneuron, or there were presyn-
# aptic GABAergic receptors present.


# \citep{AwatramaniTurecekEtAl:2005}
# To ascertain if GABAergic transmission persisted
# in still older animals (P17–P22 rats), we positioned the stim-
# ulating electrode after the slices were bathed in 500 nM
# strychnine. Under these conditions,
small, slow IPSCs (weighted time constant = 24 $\pm$ 4 ms) could be
# evoked, indicating that weak GABAergic inputs persist in
# more mature MNTB

GABAergic syanpses were evoked in mature MNTB neurons (slice preparation bathed in strychnine) with slow dynamics with a weighted time constant of 24 $\pm$ 4 ms  \citep{AwatramaniTurecekEtAl:2005}.

GABA_A receptors may also be present outside of synaptic terminals, due to the observation of enhanced recruitment when using GABA puffs  \citep{AwatramaniTurecekEtAl:2005}.




a. Golgi cells (GABA)

\begin{itemize}
\item
\item dend filter obscures PSPs
\item
\end{itemize}




* Synaptic connections
** Afferent input
*** ANF to VCN stellate cells


 [[latex:textsc][Synapse type]]: Auditory nerve fibre synapses on TS cells are glutamatergic AMPA receptors
 \citep{FerragamoGoldingEtAl:1998a,WentholdHunterEtAl:1993}.  Histological measures
 of labelled T stellate cells show the presence of glutamate and glutamine antibodies
 \citep{HackneyOsenEtAl:1990,WentholdHunterEtAl:1993}.  More advanced measures using
 electron microscopy reveal AMPA subunits, unique to the cochlear nucleus, apposing
 TS cells \citep{WangWentholdEtAl:1998}.  Pharmacologic experiments have also
 confirmed monosynaptic EPSPs from AN shocks are be blocked by the AMPA antagonist
 DNQX \citep{FerragamoGoldingEtAl:1998a}. Glutamatergic NMDA receptors may also be present at ANF synapses
 \citep[mice][]{FerragamoGoldingEtAl:1998a} and can be activated to produce large
 synaptic currents \citep{CaoOertel:2010}.  Whole cell patch recordings show NMDA
 dominance over AMPA at birth reverses during development, leaving little to no
 observable NMDA EPSCs at the soma in mature rats \citep{BellinghamLimEtAl:1998}.
# %\citep{Oertel:1983}
 Five percent of ANFs are unmyelinated type II fibres (cat: \citep{KiangRhoEtAl:1982},mice: \citep{Ehret:1979} and their axons enter the
 outer shell or GCD where they are likely to terminate on distal dendrites of T
 stellate cells using diffuse synapses, possibly mediated by NMDA receptors or
 the lack of glutamate re-uptake
 \citep{BensonBrown:2004,Ryugo:2008,RyugoHaenggeliEtAl:2003,RyugoParks:2003}.
 (cats: Kiang et al. 1982; mice: Ehret 1979)

 [[latex:textsc][Synaptic Contacts]] The ANF synaptic contacts on the cell body of T stellate
 cells are relatively small, a distinguishing contrast between the densely
 contacted D stellate cells
 \citep{Cant:1981,Cant:1982,RyugoWrightEtAl:1993,TolbertMorest:1982a,FayPopper:1994,ReddCahillEtAl:2002,RyugoWrigthEtAl:1993,Ryugo:1992,RyugoParks:2003}
 The dendritic ANF input is mostly proximal (<100 µm) with the density of
 contacts diminishing toward the distal ends \citep{SmithRhode:1989}.  T
 stellate cells have \sim 30\% somatic coverage, but less than 40\% of those
 contacts are from ANFs
 \citep{Cant:1981,Cant:1982,RyugoWrightEtAl:1993,TolbertMorest:1982a,SmithRhode:1989},
 and is highly variable (mean 13 terminals, $36 \pm 10.5$ \% of somatic
 terminals in~cat \citep*{SmithRhode:1989}, 0--6 terminals per soma in
 chinchilla \citep*{JosephsonMorest:1998}).  \citet{FerragamoGoldingEtAl:1998a}
 estimated a small number of independent ANFs (4 to 6) were needed to reach AP
 in mice T stellate cells.  Some cells had ANF synapses surrounding the axon
 initial segment \citep{JosephsonMorest:1998}.


# How chopping responses are produced is not completely understood. It has been
# suggested that stellate cells integrate input from large numbers of auditory nerve
# fibers. However, stellate cells in mice have been shown to receive input from only
# a few (four to six) sharply timed auditory nerve fiber inputs (175).  Activation of
# these inputs with trains of shocks produces entrained responses rather than
# chopping (172, 175), raising two questions: How are stellate cells prevented from
# encoding the timing of auditory nerve inputs after the initial action potential in
# response to sound, and how is their steady firing in response to tones produced
# from inputs that have strong onset transients?


 [[latex:textsc][Receptive Fields]]: The estimated receptive field of single ANFs in mice and cats ($\sim$70µm HSR,
 100µm LSR
 \citep{OertelWuEtAl:1990,Ryugo:2008,MeltzerRyugo:2006,RyugoParks:2003,Ryugo:1992,BrownBerglundEtAl:1988,RoullierCronin-SchreiberEtAl:1986,FeketeRouillerEtAl:1984})
 closely matches the dendritic width of TS cells perpendicular to the incoming ANF
 axons (75-100µm \citep[Mouse]{OertelWuEtAl:1990}).
# 0.23-0.39 oct \citep[anesthetized guinea pig][]{PalmerJiangEtAl:1996}
 The physiological receptive field is also similar between ANFs and TS cells
 (Q$_{10}=5.3$ \citep[cat][]{RhodeSmith:1986}Q$_{10}=5.52\pm1.4$ compared to
 Q$_{10}=6.3$ in ANFs \citep[guinea pig]{JiangPalmerEtAl:1996}) but varies with
 different TS cell classification subtypes (CS Q$_{10}=4$, CT Q$_{10}=2$ (low CF),
 and Q$_{10}=3.67$ (high CF) \citep[guinea pig]{PalmerWallaceEtAl:2003}) and the type
 of anaesthetic used in the study (Q$_{10}=7.4$ unanesthetised Q$_{10}=5.3$
 barbiturate \citep[cat][]{RhodeKettner:1987}).

 [[latex:textsc][Delay]]: The theoretical conductance delay from the cochlea to the position of TS cells in
 the VCN, based on the average distance and myelinated axon width, was estimated to
 be 0.5 ms \citep{Brown:1993,BrownLedwith:1990}.  Oertel and colleagues first
 calculated the delay experimentally using electrical shocks to the auditory nerve
 root in slice preparations in mice \citep[0.7 ms][]{Oertel:1983} and in chinchilla
 \citep[0.5 ms, ][]{WickesbergOertel:1993}. This was later confirmed in more studies
 with mean 0.7 ms (range 0.48--0.92 ms) \citep[mice][]{FerragamoGoldingEtAl:1998a}.


*** ANF to Tuberculoventral cells
 [[latex:textsc][Synapse type]]:
 [[latex:textsc][Synaptic Contacts]]
 [[latex:textsc][Receptive Fields]]:
 [[latex:textsc][Delay]]:

*** ANF to Golgi cells
 [[latex:textsc][Synapse type]]:

ANF\ensuremath{\rightarrow}G

AMPA (LSR), NMDA (type II ANF, granule cells)
[\citenum{Cant:1992,FerragamoGoldingEtAl:1998a,RyugoWrightEtAl:1993,Ryugo:1992,RyugoParks:2003}].
Diffuse release sites [\citenum{HurdHutsonEtAl:1999}]
Time Constant
0.4 ms (AMPA)   [\citenum{GardnerTrussellEtAl:1999}].
-- (NMDA, diffuse) [\citenum{HurdHutsonEtAl:1999}].

 [[latex:textsc][Synapse Dynamics]]:
 [[latex:textsc][Synaptic Contacts]]: Mainly contacts on thin dendrites (0.5--1 $\mu$m width)  [\citenum{BensonBrown:2004,FerragamoGoldingEtAl:1998}]
 [[latex:textsc][Receptive Fields]]:
LSR 175~$\mu$m (1 mm low CF)[\citenum{Ryugo:2008}], type II ANF less organised in GCD \citenum{WeedmanPongstapornEtAl:1996,RyugoWrigthEtAl:1993}]

Wide Dynamic range [\citenum{GhoshalKim:1997}]
250--100 $\mu$m [\citenum{FerragamoGoldingEtAl:1998a}]

 [[latex:textsc][Delay]]:
1.3 [\citenum{FerragamoGoldingEtAl:1998a}],
(type II up to 10ms, theoretical [\citenum{Brown:1993}])

** Glycinergic inputs
*** D stellate cell input to Tuberculoventral cells
 [[latex:textsc][Synapse type]]:
 [[latex:textsc][Synaptic Contacts]]
 [[latex:textsc][Receptive Fields]]:
 [[latex:textsc][Delay]]:

*** D stellate cells input to T stellate cells

 [[latex:textsc][Synapse type]]:  Evidence of glycine in the cochlear nucleus, through staining or
 immunohostochemistry, has been studied in many species including guinea pigs
 \citep{JuizHelfertEtAl:1996a,HelfertBonneauEtAl:1989,Wenthold:1987,WentholdHuieEtAl:1987,AltschulerBetzEtAl:1986,SaintBensonEtAl:1991,KolstonOsenEtAl:1992,PeyretCampistronEtAl:1987,Alibardi:2003a,MahendrasingamWallamEtAl:2004,MahendrasingamWallamEtAl:2000,BabalianJacommeEtAl:2002},
 rats
 \citep{OsenLopezEtAl:1991,Mugnaini:1985,AokiSembaEtAl:1988,GatesWeedmanEtAl:1996,Alibardi:2003,LimOleskevichEtAl:2003,SrinivasanFriaufEtAl:2004,DoucetRossEtAl:1999},
 mice \citep{WickesbergWhitlonEtAl:1991,LimOleskevichEtAl:2003,YangDoievEtAl:2002},
 cats \citep{OsenOttersenEtAl:1990,SmithRhode:1989}, baboons
 \citep{MooreOsenEtAl:1996}, gerbils \citep{GleichVater:1998}, and bats
 \citep{KemmerVater:2001a}.

Glycine GlyR receptors (mouse [\citep{FerragamoGoldingEtAl:1998a}]).
Flat vesicles (Glycine) apposed to TS units (cat [\citep{SmithRhode:1989}])
Could be mixed Gly/GABA [\citep{AltschulerJuizEtAl:1993}], most likely from periolivary terminals


 [[latex:textsc][Synaptic Contacts]]
(mice [\citep{FerragamoGoldingEtAl:1998a}])
See Table 1 (cat [\citep{SmithRhode:1989}])
$\sim$70 (high) $\sim$60 (low CF) per soma,
$\sim$1.7 per axon, FL $\sim$20 (highCF)
$\sim$10 (lowCF) (chinchilla [\citep{JosephsonMorest:1998}])
#                                & %Number
1 or 2 on soma; many gly and mixed gly/GABA on trunks; see Table 1[\citep{SmithRhode:1989}]
more FL vesicles on soma in high CF regions [\citep{JosephsonMorest:1998}]


 [[latex:textsc][Receptive Fields]]:

DS axon terminals cover 300 µm of VCN (mouse [\citep{OertelWuEtAl:1990}]).
AVCN collaterals centred on soma isofreq. as dend, 1 octave above and 2 oct below (gerbil [\citep{ArnottWallaceEtAl:2004}])
# SBW=5.1kHz \pm 4.5 kHz all Ch, CS 4.66$\pm$4.45kHz 88$\pm$19\% suppression, CT $6.28 \pm 4.65$ kHz    $96 \pm 5$\% suppression [\citep{RhodeGreenberg:1994b}]

 [[latex:textsc][Delay]]:

1.2--3.5 msec shock to AN [\citep{FerragamoGoldingEtAl:1998a,NeedhamPaolini:2003,Oertel:1983}]

The variability in delay may be due to the convalecent routes taken by the DS axons.  Some axons have been seen to travel to the DCN before returning the the VCN

Commissural DS units: 1.52 ms shock to cCN [\citep{NeedhamPaolini:2006}].

** GABAergic inputs

 [[latex:textsc][Synapse type]]: GABA_A receptor


 [[latex:textsc][Synaptic Contacts]]:
 [[latex:textsc][Receptive Fields]]:
 [[latex:textsc][Delay]]:

*** Other modulatory connections
# [[latex:textsc][Synapse type]]:
# [[latex:textsc][Synapse Dynamics]]:
# [[latex:textsc][Synaptic Contacts]]
# [[latex:textsc][Receptive Fields]]:
# [[latex:textsc][Delay]]:


* Summary of connections within the stellate microcircuit of the cochlear nucleus


Proposals for connectivity around the stellate microcircuit are summarised in Table \ref{tab:Connection}.


#+begin_latex:
\begin{landscape}
%\setcitestyle{numbers}
{\small\LTXtable{220mm}{ConnectionsTable}}
%\setcitestyle{authoryear}
\end{landscape}
#+end_latex


# Proposed neuronal connections
# The present considerations have provided evidence for the
# connections that are summarized in Fig. 15. We propose that
# T stellate cells receive excitatory, glutamatergic input from
# a small number of type I auditory nerve fibers (monosynaptic
# EPSPs) as well as through collaterals of other T stellate
# cells (late EPSPs) (Oertel et al. 1990). The topographic
# arrangement of tuberculoventral cells indicates that roughly
# the same group of auditory nerve fibers innervates tuberculo-
# ventral cells which, in turn, provide delayed, glycinergic
# inhibition (Wickesberg and Oertel 1988, 1990). D stellate
# cells contribute to the disynaptic IPSP and at high shock
# strengths can provide trains of late IPSPs to T stellate cells.
# D Stellate cells are driven by type I auditory nerve fibers
# (Oertel et al. 1990; this study), and they receive GABAergic
# inhibition, of which Golgi cells are a likely source (Mugnaini
# 1985). Golgi cells lie in the granule cell domain, away from
# the terminals of type I auditory nerve fibers. The finding
# that they are activated by shocks to the auditory nerve more
# slowly than that to T or D stellate cells in the vicinity sug-
# gests that they are activated by type II auditory nerve fibers
# (Benson et al. 1996; Ferragamo et al. 1997).

